format = """\
[╭╴](fg:arrow)\
$username\
(\
    $hostname $localip\
)\
$os\
$cmd_duration\
(\
    via \
    $python\
    $conda\
    $nodejs\
    $c\
    $rust\
    $java\
)\
$time\
$sudo\
$memory_usage\
$git_branch\
$git_status\
$git_state\
(\
    at \
    $directory\
)
[╰─](fg:arrow)$env_var$character\
"""
# Add the modules you need

# Disable the blank line at the start of the prompt
add_newline = true
continuation_prompt = '▶▶ '


palette = "normal"


[palettes.normal]
arrow = "#333533"
os = "#16f4d0"
os_admin = "#e4ff1a"
directory = "#9ffff5"
time = "#bdfffd"
node = "#a5e6ba"
git = "#f17f29"
git_status = "#DFEBED"
python = "#edf67d"
conda = "#70e000"
java = "#F86279"
rust = "#ffdac6"
clang = "#caf0f8"
duration = "#ce4257"
text_color = "#EDF2F4"
text_light = "#26272A"

# I disabled some modules (Rust, Java...) since some things aren't installed in my machine, enable them if you need.

[username]
style_user = 'bold os'
style_root = 'bold os_admin'
format = '[  $user](fg:$style) '
disabled = false
show_always = true

[os]
format = "on [($name)]($style) "
style = "bold blue"
disabled = true

[os.symbols]
Alpine = " "
Arch = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
NixOS = " "
openSUSE = " "
Pop = " "
SUSE = " "
Ubuntu = " "
Windows = " "

[directory]
format = "[$path](bold $style)[$read_only]($read_only_style) "
truncation_length = 0
style = "fg:directory"
read_only_style = "fg:directory"
before_repo_root_style = "fg:directory"
truncation_symbol = "…/"
truncate_to_repo = false
read_only ="  "

[time]
disabled = false
format = "at [󱑈 $time]($style) "
time_format = "%H:%M"
style = "bold fg:time"

[cmd_duration]
format = "took [ $duration]($style) "
style = "bold fg:duration"
min_time = 5000

[git_branch]
style = "bold fg:git"

[git_status]
style = "fg:text_color bg:git"
disabled = false

[hostname]
format = '[$ssh_symbol$hostname]($style)'
trim_at = ''

[localip]
disabled = false
format = '\[[$localipv4]($style)\] '

[docker_context]
disabled=true
symbol = " "

[env_var]
variable = 'SSH_CLIENT'
format = "[SSH](bold yellow) "

[package]
disabled=true

[fill]
symbol = " "

[sudo]
disabled = false

[memory_usage]
disabled = false
threshold = 80
format = 'RAM: [${ram}]($style)( SWAP: [${swap}]($style)) '

[nodejs]
format = "[ $symbol$version ]($style)"
style = "bg:node fg:text_light"
symbol = " "
version_format = "${raw}"
disabled=false

[python]
disabled=false
format = '[ ${symbol}${pyenv_prefix}(${version})( \($virtualenv\)) ]($style) '
symbol = " "
version_format = "${raw}"
style = "bg:python fg:text_light"
